---
title: "Capstone - earthquake plots"
author: "Rodrigo Morales"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Capstone - earthquake plots}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Cargamos packages y limpiamos datos

```{r loading, message=F, warning=F}
library(Capstone)
library(dplyr)
library(readr)
library(lubridate)
library(leaflet)

file_name <- system.file("extdata", "signif.txt", package = "Capstone")
clean_data <- file_name %>%
              readr::read_tsv() %>%
              eq_clean_data() 

```

Graficamos para Mexico los terremotos posteriores al año 2000, donde cada pop up muestra lcoation, Magnitude y Total Deaths

```{r plot, message=F, warning=F}

clean_data %>%
  dplyr::filter(COUNTRY == "MEXICO" & lubridate::year(DATE) >= 2000) %>% 
  dplyr::mutate(popup_text = eq_create_label(.)) %>% 
  eq_map(annot_col = "popup_text")

```

También podemos visualizar los terremotos historicos, como es el caso de USA y CHINA

```{r timeline, message=F, warning=F}
library(ggplot2)
clean_data %>% 
filter(COUNTRY %in% c("USA", "CHINA")) %>%
filter(DATE > "2000-01-01" ) %>%
filter(!is.na(EQ_PRIMARY) ) %>% 
ggplot( aes(x = DATE, y = COUNTRY, color = DEATHS, size = EQ_PRIMARY, fill = DEATHS))+
geom_timeline() +
geom_timelinelabel(aes(label = LOCATION_NAME, n_max = 5)) + 
        theme(legend.position="bottom",
              axis.title.x = element_blank(),
              axis.title.y = element_blank())+
        labs(size = "Richter scale value", color = "# deaths")

```



